openapi: 3.0.0
info:
  title: Admin API
  version: '1.0'
  description: 'API endpoints used for admin purposes, such as uploading a CSV to add a timetable.'
  contact:
    name: Ember
    url: 'https://www.ember.to'
    email: developer@ember.to
servers:
  - url: 'https://api.ember.to'
    description: Production
  - url: 'http://localhost:8000'
    description: Development
  - url: 'http://localhost:3100'
    description: Mock
tags:
  - name: Bulk
    description: Endpoints used for bulk admin purposes
paths:
  /bulk: {}
components:
  securitySchemes: {}