openapi: 3.0.0
info:
  title: Booking API
  version: '1.0'
  description: Ember Booking endpoints
servers:
  - url: 'https://api.ember.to'
    description: Prod
  - url: 'http://localhost:8000'
    description: Dev
  - url: 'http://localhost:3100'
    description: Mock
paths:
  /stops:
    get:
      summary: Find Stops
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/stop.v1.yaml
              examples:
                Stops List:
                  value:
                    - id: 3
                      name: Dundee
                      stop_type: 1
                    - id: 4
                      name: Dundee (Greenmarket)
                      stop_type: 2
                    - id: 5
                      name: Dundee West (Apollo Way)
                      stop_type: 2
                    - id: 6
                      name: Inchture
                      stop_type: 1
                    - id: 7
                      name: Inchture (Westbound)
                      stop_type: 2
                    - id: 8
                      name: Inchture (Eastbound)
                      stop_type: 2
                    - id: 9
                      name: Edinburgh
                      stop_type: 1
                    - id: 10
                      name: Edinburgh (Blackhall Library)
                      stop_type: 2
                    - id: 11
                      name: Edinburgh (Melville Street)
                      stop_type: 2
                    - id: 12
                      name: Ferrytoll (Park and Ride)
                      stop_type: 2
                    - id: 13
                      name: Kinross (Park and Ride)
                      stop_type: 2
                    - id: 2
                      name: Perth (Central Car Park)
                      stop_type: 2
      operationId: get-stops
      description: Get a list of possible stops
      tags:
        - Browse
      parameters: []
    parameters: []
  /journeys:
    get:
      summary: Find Journeys
      tags:
        - Browse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Journey'
              examples:
                Dundee to Edinburgh:
                  value:
                    - id: 1
                      origin:
                        departure: '2019-12-01T06:30:00Z'
                        stop_id: 1
                        stop_name: Dundee (Greenmarket)
                      destination:
                        arrival: '2019-12-01T08:15:00Z'
                        stop_id: 5
                        stop_name: Edinburgh (Melville Street)
                    - id: 1
                      origin:
                        departure: '2019-12-01T06:30:00Z'
                        stop_id: 1
                        stop_name: Dundee (Greenmarket)
                      destination:
                        arrival: '2019-12-01T07:59:00Z'
                        stop_id: 4
                        stop_name: Edinburgh (Blackhall Library)
      operationId: get-journeys
      description: This endpoint is used for finding journeys that satisfy a set of conditions
      parameters:
        - schema:
            type: integer
          in: query
          name: origin
          description: The id of the stop at the begining of the trip
          required: true
        - schema:
            type: integer
          in: query
          name: destination
          description: The id of the stop at the end of the trip
          required: true
        - schema:
            type: string
            format: date-time
          in: query
          name: departure-time-from
        - schema:
            type: string
            format: date-time
          in: query
          name: departure-time-to
        - schema:
            type: string
            format: date-time
          in: query
          name: arrival-time-from
        - schema:
            type: string
            format: date-time
          in: query
          name: arrival-time-to
        - schema:
            type: integer
            minimum: 1
          in: query
          name: passengers
          description: the amount of seats requested
          required: true
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/DiscountCards'
          in: query
          name: discounts
          description: 'a list of all applied discount cards, see DiscountCards under Models'
    parameters: []
  /upload:
    post:
      summary: Bulk Create
      tags: []
      responses: {}
      operationId: get-upload
      description: This endpoint is for adding a number of objects to the database from a `.csv` file.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        description: ''
components:
  schemas:
    Leg:
      title: Leg
      type: object
      description: The result object a client recives when searching for trips.
      x-examples:
        Dundee to Edinburgh:
          id: 1367
          origin:
            departure: '2020-05-19T23:00:00Z'
            stop_id: 1
            stop_name: Dundee (Greenmarket)
          destination:
            arrival: '2020-05-20T00:45:00Z'
            stop_id: 5
            stop_name: Edinburgh (Melville Street)
      properties:
        trip_id:
          type: integer
        origin:
          $ref: '#/components/schemas/JourneyStop'
        destination:
          $ref: '#/components/schemas/JourneyStop'
      required:
        - trip_id
        - origin
        - destination
    JourneyStop:
      title: JourneyStop
      type: object
      description: ''
      x-examples:
        Dundee (Greenmarket):
          departure: '2020-05-19T23:00:00Z'
          stop_id: 1
          stop_name: Dundee (Greenmarket)
        Edinburgh (Melville Street):
          arrival: '2020-05-20T00:45:00Z'
          stop_id: 5
          stop_name: Edinburgh (Melville Street)
      properties:
        stop_id:
          type: integer
        stop_name:
          type: string
        departure:
          type: string
          format: date-time
        arrival:
          type: string
          format: date-time
        stop_description:
          type: string
      required:
        - stop_id
        - stop_name
    Journey:
      title: Journey
      type: object
      x-tags:
        - Models
      properties:
        legs:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Leg'
        price:
          type: number
          minimum: 0
        passengers:
          type: integer
          minimum: 1
        discount_cards:
          type: array
          items:
            $ref: '#/components/schemas/DiscountCards'
      required:
        - legs
        - price
        - passengers
    DiscountCards:
      type: string
      title: DiscountCards
      enum:
        - SCOT_CONCESSION
        - SCOT_UNDER_18
      x-tags:
        - Models
